name: hrms
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  carousel_slider: 4.0.0
  animations: 2.0.1
  connectivity_plus: 2.3.6+1
  dio: 4.0.6
  logger: 1.1.0
  fluttertoast: ^8.1.1
  url_launcher: 6.1.5
  cached_network_image: 3.2.2
  progress_dialog: 1.2.4
  intl: ^0.17.0
  file_picker: 5.2.1
  linter: ^1.28.0
  mobile_scanner: ^2.1.0
  flutter_swiper: ^1.1.6
  shared_preferences: 2.0.15
  image_picker: ^0.8.6
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/vipu_group_half_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_bold.otf
        - asset: assets/fonts/montserrat_extra_bold.otf
        - asset: assets/fonts/montserrat_light.otf
        - asset: assets/fonts/montserrat_medium.otf
        - asset: assets/fonts/montserrat_regular.otf
        - asset: assets/fonts/montserrat_semi_bold.otf
        - asset: assets/fonts/montserrat_thin.otf
    - family: damion
      fonts:
        - asset: assets/fonts/damion_regular.ttf
