class Screens {

  Screens._();

  static const String LOGIN_SCREEN = "LOGIN_SCREEN";
  static const String HOME_SCREEN = "HOME_SCREEN";
  static const String QR_SCANNER_SCREEN = "QR_SCANNER_SCREEN";
  static const String MULTI_QR_SCANNER_SCREEN = "MULTI_QR_SCANNER_SCREEN";
  static const String QR_SCANNED_SCREEN = "QR_SCANNED_SCREEN";
  static const String AADHAAR_CARD_VERIFICATION_SCREEN = "AADHAAR_CARD_VERIFICATION_SCREEN";
  static const String EMPLOYEE_BASIC_DETAIL = "EMPLOYEE_BASIC_DETAIL";
  static const String EMPLOYEE_ADDRESS_DETAIL = "EMPLOYEE_ADDRESS_DETAIL";
  static const String EMPLOYEE_SKILL_DETAIL = "EMPLOYEE_SKILL_DETAIL";
  static const String EMPLOYEE_BANK_DETAIL = "EMPLOYEE_BANK_DETAIL";
  static const String CLIENT_BASIC_DETAIL = "CLIENT_BASIC_DETAIL";
  static const String CLIENT_ADDRESS_DETAIL = "CLIENT_ADDRESS_DETAIL";
  static const String CLIENT_SKILL_DETAIL = "CLIENT_SKILL_DETAIL";
  static const String CLIENT_BANK_DETAIL = "CLIENT_BANK_DETAIL";
  static const String ATTENDANCE_TYPE_ONE = "ATTENDANCE_TYPE_ONE";
  static const String ATTENDANCE_TYPE_ONE_V2 = "ATTENDANCE_TYPE_ONE_V2";
  static const String ATTENDANCE_TYPE_TWO = "ATTENDANCE_TYPE_TWO";
  static const String ATTENDANCE_TYPE_TWO_V2 = "ATTENDANCE_TYPE_TWO_V2";
  static const String MANAGE_EMPLOYEE = "MANAGE_EMPLOYEE";
  static const String MANAGE_EMPLOYEE_OPTIONS = "MANAGE_EMPLOYEE_OPTIONS";
  static const String COMPLAINS = "COMPLAINS";
  static const String VIEW_ATTENDANCE = "VIEW_ATTENDANCE";
  static const String VIEW_WORKORDER_SCREEN = "VIEW_WORKORDER_SCREEN";
  static const String VIEW_WORKORDER_SCREEN2 = "VIEW_WORKORDER_SCREEN2";

}
